### ISSUE TITLE
Capitalization of Takadao

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#10]
https://github.com/TakafulDAO/takaturn-phase-2/blob/518c7c9df3f681f248d4915619dfee7452e82190/contracts/version-2/interfaces/IZaynVaultV2TakaoDao.sol#L4

Rename the interface & file name to Takdao

**Comment by MohammedTaka** [comment]
https://github.com/TakafulDAO/takaturn-phase-2/blob/518c7c9df3f681f248d4915619dfee7452e82190/contracts/version-2/interfaces/IZaynZapV2TakaDAO.sol#L4

**Comment by maikelordaz** [comment]
Fix. Commit revise: git issue Capitalization of Takadao
