### ISSUE TITLE
Handle edge parameters for minCollateralToDeposit

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#100]
Hey Maikel, this function will fail when a called has an input `depositorIndex >= totalParticipants`. It will cause an overflow/ panic due to `0/100`
Its good practice to guard against edge parameters

Add:` require(depositorIndex < totalParticipants, "Invalid Argument");`

https://github.com/TakafulDAO/takaturn-phase-2/blob/50ea703705210193ecbc4d3d39c899b81d90c4e6/contracts/facets/GettersFacet.sol#L205-L216

**Comment by maikelordaz** [comment]
Commit d58888c. On PR
