### ISSUE TITLE
DiamondInit should be onlyOwner

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#107]
https://github.com/TakafulDAO/takaturn-phase-2/blob/6410733eb3a1c8a4af68cab43cbf84e291188e6a/contracts/DiamondInit.sol#L9

**Comment by maikelordaz** [comment]
Commit a5d08e9 on PR

**Comment by maikelordaz** [comment]
Reopen to check at the end of all fixes

**Comment by maikelordaz** [comment]
Fixed on last PR previous to testnet deploy
