### ISSUE TITLE
Move isBeneficiary function from Fund to Getters facet

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#111]
https://github.com/TakafulDAO/takaturn-phase-2/blob/218d696f9fe59ba2f12993f54e8aa1215e6fe2c0/contracts/facets/FundFacet.sol#L274

**Comment by maikelordaz** [comment]
Will remove completely. Checked and it is not called anywhere in the contracts and we have getParticipantFundSummary which return [1] is the same as isBeneficiary

**Comment by maikelordaz** [comment]
Unless it is used somewhere on the frontend or backend? @elallamTaka 
cc: @MohammedTaka

**Comment by MohammedTaka** [comment]
Let's pause this issue for now until after launch. It's not critical

**Comment by maikelordaz** [comment]
Nice. Also think is the best to confirm with the team

**Comment by elallamTaka** [comment]
Not used, remove.

**Comment by MohammedTaka** [comment]
@elallamTaka, I asked @kkharji and he confirmed that it is used still
