### ISSUE TITLE
Redundant Event

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#12]
OnParticipantUndefaulted is redundant because OnPaidContribution is enough. @MohammedTaka was there a use case I missed? 
https://github.com/TakafulDAO/takaturn-phase-2/blob/b4fede852c0544255359ff2a1156fac4448b95b6/contracts/version-2/facets/FundFacetV2.sol#L36

**Comment by maikelordaz** [comment]
Commit 511f8d9
