### ISSUE TITLE
Beneficiaries and exempted users risk expulsion if they defaulted in previous cycle

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#124]
https://github.com/TakafulDAO/takaturn-phase-2/blob/661bda1588602f584a49e9ff72f83d98ac924dad/contracts/facets/FundFacet.sol#L97

We are checking to avoid defaulting the beneficiary or exempted users. But we are not taling them out of the default state. If they have defaulted in the previous cycle, they are still in the defaulters array. 

So in the highlighted code, we must check if they are in the defaulters array and remove them from it.

I use the word array here but pretty sure an EnumerableSet is used.

**Comment by MohammedTaka** [comment]
Cc @elallamTaka

**Comment by maikelordaz** [comment]
On PR
