### ISSUE TITLE
Standardize function parameters 

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#13]
There are some functions that take in id, and some termId. Lets stick with termId. I saw this in the Fund facet

https://github.com/TakafulDAO/takaturn-phase-2/blob/bcce7951826965a9df0bd70fb73350d0777fce07/contracts/version-2/facets/FundFacetV2.sol#L76

**Comment by maikelordaz** [comment]
Done, commit 6861652
