### ISSUE TITLE
New getters function getExpulsionLimit

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#132]
This is important for the front end.

Expulsion limit is in ETH/WEI

Expulsion limit is determined by the isBeneficiary state. If the user was beneficiary, then the expulsion limit is Remaining Cycle Contributions in eth (RCC = remainingCyles * contributionAmountWei). If the user was not beneficiary, it is Single Cycle Contribution in ETH/WEI (SCC = contributionAmountWei)

**Comment by elallamTaka** [comment]
@MohammedTaka We already have this, last value getDepositorCollateralSummary. So far everything the frontend needs is available.
