### ISSUE TITLE
New getters needed

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#133]
In order to make the yield generation test, the mainnet should be fork, including our contracts, this makes harder to debug some results on tests, as I can not change the contract. This is because I have to use the deployed address as is the only one allowed by zaynfi. Right now I'm receiving 0 on `terAPY`, `userAPY`, `yieldDistributionRatio`, `totalYieldGenerated` and `userYieldGenerated`, but I'm receiving values from Zayn contracts.

So I propose one of the next two solutions
1. Two new getters, equivalent to `getDepositorCollateralSummary` and `getCollateralSummary` but to get the values of the `YieldGeneration`
2. Emit events with this values

This is because it appear this values are not stored correctly

Another possible way to debug temporarily could be to ask Ammar to add the address of the deployed contracts on my machine. But I'll have to check if every time the address is the same.

Right now I have to take our contract on the tests like this
```javascript
 // Get the contract instances
              const takaturnDiamondAddress = networkConfig[chainId]["takaturnDiamond"]
              takaturnDiamond = await ethers.getContractAt(abi, takaturnDiamondAddress)
```
This way it take the contract from mainnet
But if I can take it like this 
```javascript
     // Deploy contracts
              await deployments.fixture(["takaturn_upgrade"])
              takaturnDiamond = await ethers.getContract("TakaturnDiamond")
```
I can take it from my local machine, this way I could change the contracts locally and test

cc: @elallamTaka @MohammedTaka

**Comment by maikelordaz** [comment]
Also can also fork the testnet ,upgrade on testnet, to check there if the values are correct, and when that is checked we can upgrade the mainnet fork mainnet and test yield.

**Comment by elallamTaka** [comment]
> Also can also fork the testnet ,upgrade on testnet, to check there if the values are correct, and when that is checked we can upgrade the mainnet fork mainnet and test yield.

If you fork the testnet, how will you check if the values are correct since no yield is being generated on the testnet?

What I understood is that you want to change the contracts, namly add new getters, on the mainnet fork. How about you upgrade the contract on the mainnet fork itself and continue testing?
