### ISSUE TITLE
Wrong require on toggleOptInYG

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#134]
`toggleOptInYG` has this require
https://github.com/TakafulDAO/takaturn-phase-2/blob/e586bbdab006dc4b92fd697f23dad9b7aa56488c/contracts/facets/YGFacetZaynFi.sol#L42
But the yield is created only when the term has started. If the user is allowed to change the decision on the yield generation we should chage the require to check if the term or collateral exist, as this is the only ones that are created before the term start

cc: @elallamTaka @MohammedTaka

**Comment by MohammedTaka** [comment]
Question is then @maikelordaz,

How did I opt in? https://arbiscan.io/tx/0xfa950cb34cea75418810e5fa6c42195dd5fbb0a6c1051632b521a3de9c000fa2

![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/13a86946-4f7c-4349-831e-47e1492278c9)

**Comment by maikelordaz** [comment]
To save gas when you join the term. toggleOptInYG is not called. We only set the optIn value according if you choose true or false when joining instead of doing an external call

**Comment by MohammedTaka** [comment]
I see, we can remove that require in my opinion
