### ISSUE TITLE
Typo error on Zayn interfaces

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#135]
<h2>Situation</h2>
On the provided Zayn interfaces there are two typo errors.

1. `zapInEth` does not have the keyword `payable`. This was easy to fix at the moment as we knew that the function receive ETH, so I just add the keyword
<img width="363" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/7c09583a-f6f2-4595-8b48-44c593ab73f3">

2. `balanceOf` does not have the keyword `view`. This one it did not cause errors at the moment, but it makes some of our getters to not be able to be `view` functions
<img width="378" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/899a793e-9411-4003-9920-0e1453efa8cb">

Checking their code on the deployed contracts I found out that the function is `view` 
<img width="342" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/100a1c2e-e33b-4d1d-830a-479478d86b38">

<h2>Problems that can cause</h2>
Return values from non-view and non-pure functions are only available when the function is called and validated on-chain, because it is unknowed when the transaction will be added to the blockchain. The return value is then encoded on the transaction hash

<h2>Example</h2>
Doing this call

```javascript
const balanceOf = await zaynVault.balanceOf(termId)
console.log(`Balance of: ${balanceOf}`)
```
This is the return value all the time
<img width="310" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/80030244-8767-407b-a384-b105db2193be">

<h2>Posible solution</h2>
On the test files this can be easily fixed using the ether.js property callStatic, this one does not ask to change the state, rather ask a node to pretend the transaction succeded. So this

```javascript
const balanceOf = await zaynVault.callStatic.balanceOf(termId)
console.log(`Balance of: ${balanceOf}`)
```

Will return this
<img width="281" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/e0c6cef2-4f4d-47dd-9e11-1e946532e3cf">

The problem here is that I really don't know how the backend and frontend code will have to lead with this as I have only used callStatic on test files, I suppose it should work the same way as it is an ether.js property

<h2>Proposal</h2>
If we add the `view` keyword to the balanceOf function on the interface we can have as view functions `termAPY`, `userAPY`, `totalYieldGenerated` and `userYieldGenerated`, and then we dont have to use callStatic

<h2>Appendix</h2>
The same happen with some functions that on the interface says `pure` and on the code they are `view`

cc: @elallamTaka @MohammedTaka

**Comment by MohammedTaka** [comment]
Agreed to change the functions to view.
