### ISSUE TITLE
Bug on yield distribution ratio

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#136]
Related to git issue #133 
`yieldDistributionRatio` return the next
https://github.com/TakafulDAO/takaturn-phase-2/blob/e586bbdab006dc4b92fd697f23dad9b7aa56488c/contracts/facets/GettersFacet.sol#L556
And `currentTotalDeposit` is what is deposited from all the users that goes in the yield generation. So there are a lot of scenarios where `currentTotalDeposit` will be bigger than the collateralMembersBank. This will give as a result 0 in all those cases as solidity can not manage decimals

cc: @MohammedTaka @elallamTaka

**Comment by MohammedTaka** [comment]
Multiply it by 18 decimals. Make the 18 decimals a const

**Comment by maikelordaz** [comment]
`collateralMembersBank` and `currentTotalDeposit` are both in wei

**Comment by MohammedTaka** [comment]
Yes but they cancel eachother out. This ratio is supposed to be a percentage. Let's do 6 decimals instead then.

**Comment by elallamTaka** [comment]
Multiplying by 1e18 to convert from wei to ether will be better for accuracy. 
` return collateral.collateralMembersBank[user]  * 1e18 / yield.currentTotalDeposit; `

As an example, 
1. User A has a collateral amount of 5 ether, which is equivalent to 5 * 1e18 wei.
2. The total deposit in the contract is 8 ether, which is 8e18 wei.
3. return `(5e18 wei * 1e18) / (8e18 wei) = 0.625 * 1e18 = 6.25e17 wei`
4. 6.25e17 is 62.5% of the total deposit

We have to look at other functions that use this and adjust the logic if needed.
