### ISSUE TITLE
Opting in to Yield requires that user already paid

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#14]
Since we cannot bundle transactions yet, we need to think about how to do this. 
Maikel set a requirement in function that requires user is already part of the term to opt in. But in UI the opt in is in the same screen as paying the security. What do you think of the alternatives below?

Alternative 1: 
1. Default optin in UI is false. 
2. Remove require user to be part of term in below function
3. If user enables through UI, we call the opt in function
4. When user presses pay we call join term. 

Alternative 2: 
We modify join term to take in an extra parameter, which is the state of the toggle button

https://github.com/TakafulDAO/takaturn-phase-2/blob/68616524b603888fab40bb76f04b2a7eed34bd1f/contracts/version-2/facets/YGFacetZaynFi.sol#L59-L78

**Comment by MohammedTaka** [comment]
I prefer alternative 2, if we remove the require, the event can be triggered which would be a false alarm

**Comment by elallamTaka** [comment]
Or we only trigger it if the state is true

**Comment by MohammedTaka** [comment]
But then it would not trigger for those who are actually going to join.

Who can trigger the event if we remove the require?
- Those that have already joined (we do want this to trigger)
- Those that have not joined but are about to join (we do want this to trigger)
- Those that have not joined and will not join (we don't want this to trigger)

It's not possible to exclude those who are about to join and those who will cancel the join, unless we bundle the transaction into one, or make it so the user joining is always triggered first, then opt-in function is called.

**Comment by elallamTaka** [comment]
Hey @maikelordaz , this is how the UI looks like for when a user wants to join a term: 
![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/130288542/5119be51-decc-410b-9fbb-55960d0de463)

Notice that the Yield decision needs to be made by the user before he joins a term. This means that if they toggle before joining, the toggle transaction will fail due to the require statement you have. 

Proposed changes: 

1. toggleOptInYG should take in a second bool parameter
2. joinTerm should take in a second bool parameter
3. joinTerm should call toggleOptInYG towards the end of the function with the bool parameter. 

cc @MohammedTaka 
In the future it would be nice to let the user toggle for yield generation anytime during Accepting Security state.
This is a good example for the importance of having a doc for derived requirements for SC development lol

**Comment by maikelordaz** [comment]
Done on this commit 98a6a1b

But if there is no way to toggle the yield generation after joining the term, then maybe we can consider remove the `toggleOptInYG` function. With just the second parameter on `joinTerm` we can set the mapping `mapping(address => bool) hasOptedIn`

**Comment by elallamTaka** [comment]
> Done on this commit [98a6a1b](https://github.com/TakafulDAO/takaturn-phase-2/commit/98a6a1bbd63096e82923f1ede68eb3de2a9d4fbf)
> 
> But if there is no way to toggle the yield generation after joining the term, then maybe we can consider remove the `toggleOptInYG` function. With just the second parameter on `joinTerm` we can set the mapping `mapping(address => bool) hasOptedIn`

No its fine, we can keep it because in the future we may add the toggle button after the user joins so he can toggle anytime during accepting contribution
