### ISSUE TITLE
Track individual's terms

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#15]
https://github.com/TakafulDAO/takaturn-phase-2/blob/dadc78a9e536fffb263dbcbd5a2975ed97cfe93f/contracts/version-2/facets/TermFacetV2.sol#L107

We need a new struct with a mapping in the term that tracks an individual's joined terms. In _joinTerm, when the user succesfully joins a term, we must write to this mapping.

**Comment by maikelordaz** [comment]
This was already set on this commit 6dedf5b and on this one 6f9a9c7

**Comment by MohammedTaka** [comment]
Confirmed
