### ISSUE TITLE
User must be able to withdraw collateral when the term expires

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#151]
This issue was found by Khalid when testing the expire term functionality. When the term expires we set the `collateralMemberBank` to 0
https://github.com/TakafulDAO/takaturn-phase-2/blob/127e2f7f01fd9695531371a59663e8bd12858f64/contracts/facets/TermFacet.sol#L289
And later assign the state to releasing collateral.

But on withdrawReimbursement, there is no way to withdraw when releasing the collateral

**Comment by MohammedTaka** [comment]
You can best call the release collateral function here

**Comment by maikelordaz** [comment]
Release collateral only change the state to releasing collateral

**Comment by MohammedTaka** [comment]
Yes, but if sets it to that, the collateralMembersBank will be freed.

**Comment by maikelordaz** [comment]
Oh, I see the confussion now. Yes, of course, but when expires it moves to collateral payment bank. Instead of the solution I made on the PR I can leave the collateral on the collateral members bank

**Comment by maikelordaz** [comment]
Done. Please recheck the PR @MohammedTaka

**Comment by elallamTaka** [comment]
@maikelordaz @MohammedTaka when a term expires, we only change state, there is no need to perform any operation on the users. Basically we don't need this for loop: 
`        uint depositorsArrayLength = collateral.depositors.length;

        for (uint i; i < depositorsArrayLength; ) {
            address depositor = collateral.depositors[i];

            if (depositor != address(0)) {
                uint amount = collateral.collateralMembersBank[depositor];

                collateral.collateralPaymentBank[depositor] += amount;
                collateral.collateralMembersBank[depositor] = 0;
                collateral.isCollateralMember[depositor] = false;
                collateral.depositors[i] = address(0);
                --collateral.counterMembers;
            }

            unchecked {
                ++i;
            }
        }
`

**Comment by maikelordaz** [comment]
Merged
