### ISSUE TITLE
Storage call being called twice

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#154]
https://github.com/TakafulDAO/takaturn-phase-2/blob/bbab42744cf871c01c8d2041519b89f9173b2154/contracts/facets/CollateralFacet.sol#L492-L493

Make this a memory value and use that instead.

**Comment by maikelordaz** [comment]
Data location can only be specified for array, structs and mappings. Inside the if is ok but inside the else is not a mapping
