### ISSUE TITLE
totalYieldGenerated not calculated correctly

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#157]
https://github.com/TakafulDAO/takaturn-phase-2/blob/54db23797d55b69e31c5eb40a7426a1e2aed4977/contracts/facets/GettersFacet.sol#L598-L608

It should be `(balanceOf(termId) * getPricePerFullShare() / 1e18) - currentTotalDeposit`. This gives the ETH value of all the available shares. This result should be combined with totalWithdrawnYield and you got totalYieldGenerated.

getPricePerFullShare is a function in ZaynVault with no inputs and returns uint256.

A sanity check must be added here, where `(balanceOf(termId) * getPricePerFullShare()) > currentTotalDeposit` before doing this. If this is not the case it returns only totalWithdrawnYield

**Comment by maikelordaz** [comment]
Merged
