### ISSUE TITLE
Missing getter functions

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#16]
We are missing functions that track an individual's term. These are from the new architecture proposal.

![Screenshot_20230830_095343_Dropbox](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/038af45e-a75d-4cdb-b29d-04caebf27d22)

**Comment by maikelordaz** [comment]
Some of this getters have not written yet, other ones has other names. Let me write the ones that are missing, think their two and match the other names

**Comment by maikelordaz** [comment]
67f5603

**Comment by MohammedTaka** [comment]
Confirmed
