### ISSUE TITLE
userYieldGenerated should be divided by 18 decimals

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#164]
https://github.com/TakafulDAO/takaturn-phase-2/blob/d5f56a8c42a86ff3ebe91fd54b20d27f1c1e94f4/contracts/facets/GettersFacet.sol#L653

totalYieldGenerated and yieldDistributionRatio are both 18 decimals. So the answer should be divided by 18 decimals again.

cc @elallamTaka

**Comment by maikelordaz** [comment]
Merged
