### ISSUE TITLE
Rename 2 functions

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#17]
https://github.com/TakafulDAO/takaturn-phase-2/blob/dadc78a9e536fffb263dbcbd5a2975ed97cfe93f/contracts/version-2/facets/GettersFacetV2.sol#L291

https://github.com/TakafulDAO/takaturn-phase-2/blob/dadc78a9e536fffb263dbcbd5a2975ed97cfe93f/contracts/version-2/facets/GettersFacetV2.sol#L301

These 2 functions should not hav
![Screenshot_20230830_095723_Dropbox](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/fa4bd76f-bc1f-46eb-9f59-00cacc5fbe8a)
e any reference to USD or ETH. This includes the variables etc.

**Comment by maikelordaz** [comment]
Commit dfc875a
