### ISSUE TITLE
Use average exchange rate instead of live price

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#18]
We must figure out how to make the price more fair and avoid edge cases where ETH dips or raises sharply and then returns to a normal price.

![Screenshot_20230830_100540_Dropbox](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/be8cd8d7-a115-4eba-803d-a46458d7c382)

**Comment by maikelordaz** [comment]
Moved to jira
