### ISSUE TITLE
Redundant event

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#20]
https://github.com/TakafulDAO/takaturn-phase-2/blob/a42b7453060e554137076b8e67a83f603a70e589/contracts/version-2/facets/FundFacetV2.sol#L591-L599

On expulsion 2 events are being emitted, OnTotalParticipantsUpdated and OnDefaulterExpelled.
Someone being expelled implies that the total number of participants reduced by 1. I think OnTotalParticipantsUpdated  is redundant unless you see a use case.

**Comment by maikelordaz** [comment]
Commit 7682e22
