### ISSUE TITLE
Redundant for loop

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#21]
There is a variable called counterMembers. This can be used to find the index rather than the for loop. 
You can immediately get the min collateral: minCollateralToDeposit(term, counterMembers);  

https://github.com/TakafulDAO/takaturn-phase-2/blob/a42b7453060e554137076b8e67a83f603a70e589/contracts/version-2/facets/TermFacetV2.sol#L130-L145

**Comment by maikelordaz** [comment]
Commit 71b95ca
