### ISSUE TITLE
Rename _liquidateCollateral to spendCollateral

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#22]
https://github.com/TakafulDAO/takaturn-phase-2/blob/a42b7453060e554137076b8e67a83f603a70e589/contracts/version-2/facets/CollateralFacetV2.sol#L76

Liquidating implies exchanging the ETH to something else, we are not doing this.

**Comment by maikelordaz** [comment]
Commit 7682e22
