### ISSUE TITLE
Expellants array not initialized

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#25]
https://github.com/TakafulDAO/takaturn-phase-2/blob/a42b7453060e554137076b8e67a83f603a70e589/contracts/version-2/facets/CollateralFacetV2.sol#L292

Shouldn't this array be initialized somehow? Or is this not needed?

**Comment by maikelordaz** [comment]
The memory array can be set like that as a dynamic array or initialized with a fixed length. It can be initialized with the size of the defaulters, but as we dont know for certain how many expellants there will be, it can be left with a lot of addresses zero to fill all the spaces
