### ISSUE TITLE
Invalid comment

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#26]
https://github.com/TakafulDAO/takaturn-phase-2/blob/a42b7453060e554137076b8e67a83f603a70e589/contracts/version-2/facets/CollateralFacetV2.sol#L54

@param defaulters Address that was randomly selected for the current cycle

should be:

@param defaulters Addressess of all defaulters of the current cycle

**Comment by maikelordaz** [comment]
3fce8da
