### ISSUE TITLE
USDC/stabletoken is never shared upon expulsion 

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#27]
https://github.com/TakafulDAO/takaturn-phase-2/blob/98a6a1bbd63096e82923f1ede68eb3de2a9d4fbf/contracts/version-2/facets/CollateralFacetV2.sol#L283

This makes this redundant.

**Comment by maikelordaz** [comment]
Fixed by @MohammedTaka on commit 386bc06
