### ISSUE TITLE
Payment exemption check is wrong

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#29]
https://github.com/TakafulDAO/takaturn-phase-2/blob/4892dcff1dea32a2fff6c27d70a7eff6b667bd69/contracts/version-2/facets/FundFacetV2.sol#L220

This check looks if you have been beneficiary before the expellant's cycle. However, it should check if you have been beneficiary before the expellant got expelled.

**Comment by maikelordaz** [comment]
Solved by @MohammedTaka on commit 7b8bef4
