### ISSUE TITLE
yieldUsers's function

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#3]
https://github.com/TakafulDAO/takaturn-phase-2/blob/518c7c9df3f681f248d4915619dfee7452e82190/contracts/version-2/libraries/LibYieldGeneration.sol#L23C19-L23C29

What's the function of yieldUsers?

**Comment by maikelordaz** [comment]
On `_createYieldGenerator` I'm storing there all the ones who opted in, so it's easy to track them, were thinking on functions like `emptyCollateralAfterEnd` have an array with only the ones who opted in would be easier

**Comment by MohammedTaka** [comment]
Understood
