### ISSUE TITLE
Incomplete function

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#30]
https://github.com/TakafulDAO/takaturn-phase-2/blob/d65f2fb3b76d7429691756a8f099d127f54b202f/contracts/version-2/facets/CollateralFacetV2.sol#L115

@maikelordaz please tackle this as I didn't have time to add this functionality. We need to get the expellantBeneficiaryCycle: The cycle this expellant was supposed to be beneficiary.

**Comment by maikelordaz** [comment]
@MohammedTaka please check on the fund facet the function `_actualDefaulters` there I check the ones who are real defaulters and who doesn't (because is a beneficiary or does not have to pay) and return an address array, with that address array I'm calling `requestContribution` from `_awardBeneficiary`. If I understand correctly is that what you want to do with `_exemptNonBeneficiariesFromPaying`?

**Comment by MohammedTaka** [comment]
Yes and no. I want to keep track on what cycle someone is exempt. What happens here with _actualDefaulters and without the exemption logic, the user still defaults but is not taken with the request contribution function.

We must make it so the user simply doesn't default at all. That's where the exemption comes in. We check this value and if it's true, the userndoesn't have to pay. It is important to do it like this because:

- We must block regular payment
- We must block autopay for this user at this cycle
- We must make sure the user isn't set to "default" even if no collateral will be taken
- Wirh exemption, it is easy for the front end to know when someone is exempted from paying and can promptly disable the button

What i want with _exemptNonBeneficiariesFromPaying is the cycle where the expellant was to be beneficiary. If we have that and use exekpti9n, _actualDefaulters will not be needed

**Comment by maikelordaz** [comment]
Commit 63b56a2

**Comment by MohammedTaka** [comment]
Looking good,

Can we add a break to the loop if the if-statement succeeds?
https://github.com/TakafulDAO/takaturn-phase-2/blob/63b56a2b651d92103ba93ae57096915b81cf4488/contracts/version-2/facets/CollateralFacetV2.sol#L132

**Comment by MohammedTaka** [comment]
Also, actualDefaulters function should not be needed anymore. Because the exemption prevents those from defaulting. The beneficiary is also already prevented from defaulting. So it would run run the code in the function but return the same array of defaulters.

https://github.com/TakafulDAO/takaturn-phase-2/blob/be0842a2fb1e3132fad9e920f3e1005391c5d218/contracts/version-2/facets/FundFacetV2.sol#L440

**Comment by maikelordaz** [comment]
Break statement on commit 5cf0f61
Removed functionon commit a1a5bbd
