### ISSUE TITLE
= should be +=

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#32]
https://github.com/TakafulDAO/takaturn-phase-2/blob/8262af13929ce2f3ef982b6e990c105133937482/contracts/version-2/facets/FundFacetV2.sol#L492

With the frozen money pot solution, it is possible that the beneficiariesPool already has a value added to it due to _requestContribution. So we must add to this value instead of setting it.

**Comment by maikelordaz** [comment]
Good catch.
Commit 1d36341
