### ISSUE TITLE
How many decimals is term.contributionAmount supposed to be?

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#33]
https://github.com/TakafulDAO/takaturn-phase-2/blob/8262af13929ce2f3ef982b6e990c105133937482/contracts/version-2/libraries/LibTermV2.sol#L31

Please make sure decimals are consistent with all usages of this variable

**Comment by MohammedTaka** [comment]
Different usages found:

https://github.com/TakafulDAO/takaturn-phase-2/blob/8262af13929ce2f3ef982b6e990c105133937482/contracts/version-2/facets/CollateralFacetV2.sol#L453
https://github.com/TakafulDAO/takaturn-phase-2/blob/8262af13929ce2f3ef982b6e990c105133937482/contracts/version-2/facets/CollateralFacetV2.sol#L454

https://github.com/TakafulDAO/takaturn-phase-2/blob/8262af13929ce2f3ef982b6e990c105133937482/contracts/version-2/facets/FundFacetV2.sol#L401


Whatever we choose, mention how much decimals in the comments of the variable.

**Comment by elallamTaka** [comment]
This is a big catch. The beneficiary pool stores it as 6 decimals. 
https://github.com/TakafulDAO/takaturn-phase-2/blob/8262af13929ce2f3ef982b6e990c105133937482/contracts/version-2/facets/FundFacetV2.sol#L492

Input to term creation should be in $ (e.30) but managing and storing should be in 6 decimals.  
Also, in the future, we may deal with stable coins with different decimal places.

**Comment by maikelordaz** [comment]
Yes it is stored, on the term facet, as the user inputs, without decimals

https://github.com/TakafulDAO/takaturn-phase-2/blob/431e2ab1d2efa0c9b34c4c81cb0df3ab2213bd81/contracts/facets/TermFacet.sol#L90

Then on the fund facet it is used for transfers from the user to pay the contribution on `_payContributionSafe` and `_payContribution`

Here
https://github.com/TakafulDAO/takaturn-phase-2/blob/431e2ab1d2efa0c9b34c4c81cb0df3ab2213bd81/contracts/facets/FundFacet.sol#L379

And here
https://github.com/TakafulDAO/takaturn-phase-2/blob/431e2ab1d2efa0c9b34c4c81cb0df3ab2213bd81/contracts/facets/FundFacet.sol#L399

And on `_awardBeneficiary` it used to stored the beneficiary pool, with six decimals

https://github.com/TakafulDAO/takaturn-phase-2/blob/431e2ab1d2efa0c9b34c4c81cb0df3ab2213bd81/contracts/facets/FundFacet.sol#L480

When the user wants to withdraw the fund, the transfer comes from what it is stored on beneficiaries pool

https://github.com/TakafulDAO/takaturn-phase-2/blob/431e2ab1d2efa0c9b34c4c81cb0df3ab2213bd81/contracts/facets/FundFacet.sol#L527

Lastly on the Collateral facet when it is used to change something en the beneficiaries pool it is with 6 decimals, as in here

https://github.com/TakafulDAO/takaturn-phase-2/blob/431e2ab1d2efa0c9b34c4c81cb0df3ab2213bd81/contracts/facets/CollateralFacet.sol#L463

And when it is comparing to ether it used 18 decimals like this

https://github.com/TakafulDAO/takaturn-phase-2/blob/431e2ab1d2efa0c9b34c4c81cb0df3ab2213bd81/contracts/facets/CollateralFacet.sol#L332

**Comment by maikelordaz** [comment]
Think the implementation is correct, but I'll test it. I changed on the term facet the call to the depositYG function to only happen if there is something to deposit, That way it is not necesary to wait for the zaynfi address and the tests runs fine. I'll write one test to check the decimals behavior
