### ISSUE TITLE
Include an expelled check in getJoinedTermsByState

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#38]
https://github.com/TakafulDAO/takaturn-phase-2/blob/7cb0229c21d5c0d6098308ec5737950916d21dbb/contracts/version-2/facets/GettersFacetV2.sol#L55

Make this optional, add a boolean input "includeExpulsions".

Makes it easier for the front end to call

**Comment by MohammedTaka** [comment]
@elallamTaka I don't know if this is needed but I assumed it would be essier for the front/back end. If not then I will close this issue.

**Comment by elallamTaka** [comment]
@MohammedTaka hmm not currently. Right now this data is being fetched from the backend. But we can revise this after launching because we want to decrease dependency on backend and increase dependency on blockchain.
