### ISSUE TITLE
Rename APR to APY

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#39]
https://github.com/TakafulDAO/takaturn-phase-2/blob/45a3928825de69548bc6a438d6f31951f0b1e187/contracts/facets/GettersFacet.sol#L374

https://github.com/TakafulDAO/takaturn-phase-2/blob/45a3928825de69548bc6a438d6f31951f0b1e187/contracts/facets/GettersFacet.sol#L389

Including all other references to APR.
Design/front-end will use APY so we want to remain consistent on that.

**Comment by maikelordaz** [comment]
Commit c7187e5
