### ISSUE TITLE
These consts should be either a mapping or specifically mention ZaynFi in their name

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#4]
https://github.com/TakafulDAO/takaturn-phase-2/blob/518c7c9df3f681f248d4915619dfee7452e82190/contracts/version-2/libraries/LibYieldGeneration.sol#L15C8-L15C8

**Comment by maikelordaz** [comment]
Commit bf1ba52

**Comment by MohammedTaka** [comment]
Opted for making it a mapping for future-proofing
