### ISSUE TITLE
Add new function to zaynfi interface

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#40]
https://github.com/TakafulDAO/takaturn-phase-2/blob/c7187e50b7db3232ec8ac5f1757e8fa00898728c/contracts/interfaces/IZaynVaultV2TakaDao.sol#L4

`function getPricePerFullShare() external view returns (uint256);`

**Comment by maikelordaz** [comment]
Commit 70e16bb
