### ISSUE TITLE
(LOW PRIORITY) Create an onlyOwner function that will transfer all balance of a specific term to owner wallet

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#41]
We need this function for goerli testing only because goerli eth is getting harder to find. For terms we created for testing and want to take back the eth we can have a function: withdrawAllbalance(termID) that transfers all eth and usdc to owenr address. But this will only exist on the goerli, not mainnet. 

Low priority, do not have to implement now.

**Comment by maikelordaz** [comment]
Commit 0325802

**Comment by maikelordaz** [comment]
Merged
