### ISSUE TITLE
The min collateral during the join period can change

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#42]
https://github.com/TakafulDAO/takaturn-phase-2/blob/e30962b252c74e6d14823f6622e395dd67fad17d/contracts/facets/GettersFacet.sol#L176

Should we make the eth price fixed during this time? It could be the case that the first person joins while ETH is high and second person joins while ETH is loe, making the second person have more ETH than the first person.

**Comment by maikelordaz** [comment]
Fixed to the price when the first one joins?

**Comment by MohammedTaka** [comment]
Agreed during meeting to keep it as is because of the join period being only a week
