### ISSUE TITLE
Double decimals multiply?

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#43]
https://github.com/TakafulDAO/takaturn-phase-2/blob/e30962b252c74e6d14823f6622e395dd67fad17d/contracts/facets/GettersFacet.sol#L351

https://github.com/TakafulDAO/takaturn-phase-2/blob/e30962b252c74e6d14823f6622e395dd67fad17d/contracts/facets/GettersFacet.sol#L181

With this function call, it multiplies by 18 decimals as input. But inside the function, it is multiplying by 18 decimals again. Please check all uses of this function

**Comment by maikelordaz** [comment]
ethPrice is with 18 decimals so here `uint USDAmountInEth = (USDAmount * 10 ** 18) / ethPrice;` it corrects to the number of decimals given in the input, as on some we need the `contributionAmountWei` the input needs to have 18 decimals. Think can be improved when we add the decimals as a parameter to allow another token for the contribution. Although right know all the use case are with wei, can return it as that to avoid confusions
