### ISSUE TITLE
Aggregator mapping key is wrong

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#44]
https://github.com/TakafulDAO/takaturn-phase-2/blob/e30962b252c74e6d14823f6622e395dd67fad17d/contracts/facets/GettersFacet.sol#L333

It's being stored/used as USD/USDC but it should be USDC/USD

https://data.chain.link/arbitrum/mainnet/stablecoins/usdc-usd

**Comment by MohammedTaka** [comment]
Implementation seems correct but the naming is wrong

**Comment by maikelordaz** [comment]
Commit de7f912
