### ISSUE TITLE
Rename function to remove confusion 

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#45]
The first function must be called getRemainingRegistrationTime. Confirm that it gets the **time remaining to pay security.** 
The other function is used to get the **time remaining to pay contributions.** 

https://github.com/TakafulDAO/takaturn-phase-2/blob/e30962b252c74e6d14823f6622e395dd67fad17d/contracts/interfaces/IGetters.sol#L22

https://github.com/TakafulDAO/takaturn-phase-2/blob/e30962b252c74e6d14823f6622e395dd67fad17d/contracts/interfaces/IGetters.sol#L149

**Comment by maikelordaz** [comment]
Commit e5320f7
