### ISSUE TITLE
Claim Yield after user claims security

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#48]
We want the user to have both his security and yield back in one transaction (UXUI requirement). Basically to batch the transactions.

So after we transfer the eth, call `claimAvailableYield(uint termId, address user)` inside `withdrawlCollateral`

https://github.com/TakafulDAO/takaturn-phase-2/blob/e858528801f178a6137642dfe1f7cf863b6bf1cc/contracts/facets/CollateralFacet.sol#L168-L193

**Comment by maikelordaz** [comment]
Commit 8007578
