### ISSUE TITLE
Create Getter to get withdrawable collateral for a user

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#49]
We need a getter function that takes in a termID and a User and returns how much they can partially withdraw in wei. 
Suggested name: `getPayableUserBalance `? or `getWithdrawableUserBalance`

https://github.com/TakafulDAO/takaturn-phase-2/blob/e858528801f178a6137642dfe1f7cf863b6bf1cc/contracts/facets/CollateralFacet.sol#L180-L187

**Comment by maikelordaz** [comment]
Commit 1f170f7

**Comment by maikelordaz** [comment]
Have not read the issue about the available yield when the user withdraws the collateral when I did the first commit. Added also the available yield in this getter. Commit 81908f5
