### ISSUE TITLE
Event signature Hashes

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#50]
@elallamTaka on commit d10a0cb I wrote two scripts to help the backend team. 
One returns all the current contract addresses (diamond proxy and facets implementation), to use it run on the terminal `yarn contractsInfo`
The second script return the hashes you were asking, this way if they need us to add a new parameter to an event, when the changes are deployed the ABI file on the deployments folder will update, and they only have to run the command `yarn eventSignatures` on the terminal and all the signatures hashes will log. Hope this helps

**Comment by elallamTaka** [comment]
Hey @maikelordaz, this is exactly what I was looking for. Thanks. The caveat is that the backend dev will have to set up the env variable to run the command although this script doesn't need hardhat. So the alternative is to run `node scripts/eventSignatures.js`

**Comment by maikelordaz** [comment]
Exactly, for this script they don't need hardhat but need ethers as I used `ethers.utils.keccak256` and `ethers.utils.toUtf8Bytes` but they can keccak with any library they use. So they can have on their source code the script and ABI. On the deployments folder there are two ABIs for the diamond `TakaturnDiamond_DiamondProxy.json` is the ABI that is uploaded to Arbiscan and only has the proxy events (think there is only one for diamond cut). And the other file is `TakaturnDiamond.json` this one is the one they have to use, it has all the events from the proxy and from the facets. The script will return the correct hashes except when an event has as parameter an array or a struct, we do not have any event like that so there is no problem. As long as there is no change on the events they don't need to be updating the ABI file for the hashes everytime
