### ISSUE TITLE
[Critical] Function must take in termID rather then struct

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#51]
This function can be called externally and is used to get the min deposit on the frontend. Input type must be uint.
Upgrade testnet contracts after this change.

https://github.com/TakafulDAO/takaturn-phase-2/blob/d10a0cb761c4066bd67a2d4c68b2a64337df9289/contracts/facets/GettersFacet.sol#L176-L185

**Comment by maikelordaz** [comment]
Changed param on commit a910256

**Comment by maikelordaz** [comment]
New deployments on commit 8c8073c
