### ISSUE TITLE
Registration period only starts after the first deposit, not after the creation time of the term

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#52]
Registration period starts after the firstDepositTime. Otherwise we will have floating terms out there that expire with no initial users. @MohammedTaka 

https://github.com/TakafulDAO/takaturn-phase-2/blob/2b7a056309b8583a2e19bce8b9b5ea666f0bdb89/contracts/facets/TermFacet.sol#L121-L124

**Comment by maikelordaz** [comment]
Commit 1d72b75 

Do I upgrade?

**Comment by elallamTaka** [comment]
Yes please @maikelordaz
