### ISSUE TITLE
Add the users expulsion limit to getter

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#55]
Suggest we add the expulsion limit for a user in wei to this getter **if its user specific.**
@MohammedTaka Can you confirm this:

```
if (user was not beneficiary)
    limit = contributionAmount
else
    limit = RCC

```

https://github.com/TakafulDAO/takaturn-phase-2/blob/cf9c473d69a7fd1d2b6106c592ad13ca06bd66bf/contracts/interfaces/IGetters.sol#L72

**Comment by maikelordaz** [comment]
Commit cc58f0c

**Comment by elallamTaka** [comment]
@maikelordaz 
1. I think the logic in the body is switched?
2. Can you please update IGetter description

**Comment by maikelordaz** [comment]
Yes I was mistaken but fixed it, forgot to write it here, the last commit is the ABI and the one before that one is the fix. Ok I'll update the comments on the interface, believe also are missing other comments will do those ones also
