### ISSUE TITLE
Bug on withdrawFund

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#56]
@elallamTaka I found this issue on the withdrawFund function

https://github.com/TakafulDAO/takaturn-phase-2/blob/420aebf54416e8b7930d9bd5679b3230be7d44c6/contracts/facets/FundFacet.sol#L279

If the user is under collaterized, it wont be able to withdraw the fund when the fund is closed, as it was a simple fix I applied the next solution and upgrade 

```solidity
       if (hasFrozenPool) {
            bool freeze = _freezePot(LibTerm._termStorage().terms[termId], fund, msg.sender);

            if (fund.currentState != LibFund.FundStates.FundClosed) {
                require(!freeze, "Need at least 1.1RCC collateral to unfreeze your fund");
            }

            _transferPoolToBeneficiary(termId, msg.sender);
        }
```

Have not pushed it to not mess the branch peckshield will be reviewing, and wanted to ask you if I create a new branch for this? or wait? or push to the current one

**Comment by elallamTaka** [comment]
Please push it, its just an additional line @maikelordaz

**Comment by maikelordaz** [comment]
Done
