### ISSUE TITLE
Arithmetic error

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#59]
There was an arithmetic error on withdrawCollateral. Fixed on 33be91e Redeployed to be able to generate the OnCollateralWithdrawal event

@elallamTaka

**Comment by elallamTaka** [comment]
@maikelordaz This issue also exists on main and audit branch. Its not ideal to fix issues existing on other branches as well without having a merge strategy. 
For this issue specifically, create a PR for the security branch as well please
