### ISSUE TITLE
Remove registration period check in JoinTerm

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#63]
The registration period is there to prevent terms from starting before a certain time, but it should not prevent new users from joining if there is space. Remove the required check below. 

The rule is basically: "The 1st cycle can only start after the registration period, & anyone can join before the 1st cycle starts".

cc @MohammedTaka 

https://github.com/TakafulDAO/takaturn-phase-2/blob/ad32a72347d4a92c5d59a8527d308bccbe2434a6/contracts/facets/TermFacet.sol#L124-L129

**Comment by MohammedTaka** [comment]
Agreed

**Comment by maikelordaz** [comment]
Commit 9aee48e
