### ISSUE TITLE
IsParticipant is not set until after the fund starts

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#64]
https://github.com/TakafulDAO/takaturn-phase-2/blob/90dfaea9025b308ea72eaf8f321ecca9b335a4e2/contracts/facets/YGFacetZaynFi.sol#L104

You must use isCollateralMember because that is set before the fund starts. And toggleYG can only happen before the fund starts

**Comment by maikelordaz** [comment]
Commit dc5f197
