### ISSUE TITLE
PVE001: Public Exposure of Privileged Functions

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#71]
= `toggleOptInYG` fixed on commit 2303cfd
- `initFund` was moved to a library and is now an internal function. A new library to manage some internal functions from the FundFacet was created on commit 0cce8b4 and deb713f
- `setStateOwner` was removed on commit and a new library was created `LibCollateralStorage` 0dd788b

**Comment by maikelordaz** [comment]
cc: @elallamTaka @MohammedTaka @ranimes

**Comment by MohammedTaka** [comment]
For context
![Screenshot_20230929_080544_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/6ecbe73b-d261-4c04-9e98-6a73aa7fe5bb)

**Comment by maikelordaz** [comment]
Fixed
