### ISSUE TITLE
PVE002: Potential Reentrancy Risk in Repeatedly Claiming Yields

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#72]
Fixed on commit 5738367

**Comment by maikelordaz** [comment]
cc: @elallamTaka @MohammedTaka @ranimes

**Comment by MohammedTaka** [comment]
For context

![Screenshot_20230929_080555_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/ee73b1d9-ec7b-4b44-8f46-b3c2f169dadd)

**Comment by maikelordaz** [comment]
Fixed and merged
