### ISSUE TITLE
PVE003: Possibly Unexpected Fund Withdrawal in FundFacet

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#73]
Fixed on commit 19cfbeb

**Comment by maikelordaz** [comment]
cc: @elallamTaka @MohammedTaka @ranimes

**Comment by MohammedTaka** [comment]
For context

![Screenshot_20230929_080603_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/29a416dd-6c4a-4f43-a340-4302725d9d2c)

**Comment by maikelordaz** [comment]
Fixed and merged
