### ISSUE TITLE
PVE006-2: Revisited Yield APY Calculation in GettersFacet

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#74]
Fixed on commit 10929fa

**Comment by maikelordaz** [comment]
cc: @elallamTaka @MohammedTaka @ranimes

**Comment by MohammedTaka** [comment]
For context

![Screenshot_20230929_080640_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/f7e02faf-456c-4f45-92a6-e1ca3bc7fc65)

**Comment by maikelordaz** [comment]
Fixed and merged
