### ISSUE TITLE
N2: Removal of Unused State/Code/Event

### ISSUE THREAD

**Issue by maikelordaz** [TakafulDAO/takaturn#75]
Fixed on commit 6564ee9

**Comment by maikelordaz** [comment]
cc: @elallamTaka @MohammedTaka @ranimes

**Comment by MohammedTaka** [comment]
For context

![Screenshot_20230929_080701_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/a57c39f4-342f-479a-96e3-dd72ac8959f2)

**Comment by maikelordaz** [comment]
Fixed and merged
