### ISSUE TITLE
PVE004: Accommodation of Non-ERC2-Compliant Tokens

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#76]
For context
![Screenshot_20230929_080610_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/cabceb3c-a7ed-4b12-a65c-0dd7cacb17e4)

![Screenshot_20230929_080617_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/4c689934-8b94-432d-9c30-a3a391f6c68a)

Will fix in phase 3 with multi-coin feature

**Comment by maikelordaz** [comment]
To be deployed on next phase
