### ISSUE TITLE
PVE005: Incorrect Withdrawal User Amount Calc. In GettersFacet

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#77]
For context

![Screenshot_20230929_080624_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/67e11fae-b308-4a9a-b2ea-ce1404b552ff)

Won't fix because yield should not impact partial withdrawals. Won't fix

**Comment by maikelordaz** [comment]
Expeted behaviour
