### ISSUE TITLE
PVE006: Revisited Total Yield Calculation in GettersFacet

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#78]
For context

![Screenshot_20230929_080632_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/a7b21ff3-e26e-4521-b3de-eaebedd05173)

This is indeed an issue but proposed fix is not correct. See my comment on screenshot.

**Comment by MohammedTaka** [comment]
@maikelordaz make a new a new internal function

`function _sharesToEth(uint currentShares, uint totalDeposit, uint totalShares) internal pure returns {
    return currentShares * totalDeposit / totalShares; 
}`

**Comment by maikelordaz** [comment]
The `_sharesToEth` will replace `IZaynVaultV2TakaDao(yield.providerAddresses["ZaynVault"]).balanceOf(termId))`?

**Comment by MohammedTaka** [comment]
Yes it will replace that.

**Comment by maikelordaz** [comment]
Changes related to PVE006 completed on commit a4230d3 cc: @ranimes

**Comment by maikelordaz** [comment]
Fixed and merged
