### ISSUE TITLE
PVE007: Trust Issue of Admin Keys (Questionable if EOA)

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#79]
For context

![Screenshot_20230929_080647_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/df5979ce-72eb-4ad4-9924-f89f115690c4)

Contract is out of scope and only used for testing purposes on testnet

**Comment by maikelordaz** [comment]
Out of scope
