### ISSUE TITLE
Wrong formula on userYieldGenerated

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#8]
https://github.com/TakafulDAO/takaturn-phase-2/blob/518c7c9df3f681f248d4915619dfee7452e82190/contracts/version-2/facets/GettersFacetV2.sol#L389

The correct formula is:
withdrawnYield[user] + totalYieldGenerated() * yieldDistributionRatio()

**Comment by maikelordaz** [comment]
Commit dbf80d8

**Comment by MohammedTaka** [comment]
Confirmed
