### ISSUE TITLE
N1: Implicit Decimals Assumption of Stablecoins

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#80]
For context:

![Screenshot_20230929_080654_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/97f8224f-a7b1-4d7f-9aea-5764ccaca171)

Will fix with phase 3, see issue #34.

**Comment by maikelordaz** [comment]
To be deployed on next phase
