### ISSUE TITLE
Q1: Revisited _solveDefaults() Logic

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#81]
For context

![Screenshot_20230929_080716_Drive](https://github.com/TakafulDAO/takaturn-phase-2/assets/129737769/c389cf4d-35df-4ab7-aeb0-debfe294ed6d)

Found issue is invalid, current logic is correct. Won't fix

**Comment by maikelordaz** [comment]
Expected behaviour
