### ISSUE TITLE
Critical: calling yieldDistributionRatio before a fund starts causes division by 0

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#83]
Call fails due to division by 0 if this getter was called and no one opted in for yield. 
Add a condition, `if yield.currentTotalDeposit == 0 then return 0`
https://github.com/TakafulDAO/takaturn-phase-2/blob/6410733eb3a1c8a4af68cab43cbf84e291188e6a/contracts/facets/GettersFacet.sol#L471-L480

**Comment by maikelordaz** [comment]
Commit 223a5a9 and create PR

**Comment by elallamTaka** [comment]
@maikelordaz the commit you provided just shows changes to json files

**Comment by maikelordaz** [comment]
You are right, sent you the previous one. This is the correct, is on the current PR e623306

**Comment by maikelordaz** [comment]
@elallamTaka merged on commit a4230d3. Deployed and new ABIs on commit 466b617
