### ISSUE TITLE
Turn neededShares into a new function _ethToShares

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#86]
https://github.com/TakafulDAO/takaturn-phase-2/blob/6410733eb3a1c8a4af68cab43cbf84e291188e6a/contracts/facets/YGFacetZaynFi.sol#L55

Related to PVE006-02

(collateralAmount * yield.totalShares) / yield.totalDeposit

This function can be in the tield generation library

**Comment by maikelordaz** [comment]
Commit 19f00ff
