### ISSUE TITLE
Create Unit Test for Frozen Money Pot Scenario 

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#88]
Objective: Tests if the users money pot is frozen based on flowchart conditions

**Comment by MohammedTaka** [comment]
Flowchart in question

https://drive.google.com/file/d/1RWrLJIJTUxdwEJxQNY3y3m3zs0jE2oWG/view?usp=drivesdk

**Comment by maikelordaz** [comment]
Commits 7d2805e and 2b402c8. Create PR

**Comment by maikelordaz** [comment]
For context. Covered the next on the unit tests
![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/74b4c548-8152-4299-835c-8f04b354696a)

**Comment by elallamTaka** [comment]
Moved to Jira https://takadao.atlassian.net/jira/software/c/projects/TT/boards/16/backlog?selectedIssue=TT-1433
