### ISSUE TITLE
Create Unit Tests for Yield Generation (On Fork)

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#89]
- [x] Users can only opt in and out during the registration period. 
- [ ] Users collateral who opted in only gets zapped 
- [ ] Zaynfi returns the correct balance of shares
- [ ] The correct distribution ratio is calculated
- [ ] Our testnet and mainnet addresses are white listed
- [ ] Yield is claimable when a withdrawal happens upon default, early withdrawal, expulsion or end of the term
- [ ] withdrawal form the yield generation provider can only be done by the smart contract
- [ ] No errors when there is eth withdrawn with no available yield
- [ ] Term must have 0 shares after everyone withdraws their collateral
- [ ] The behaviour of a participant doesn't affect others yield (create 2 terms with different user behaviours but with one constant behaviour)

**Comment by maikelordaz** [comment]
<img width="693" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/a6426cfd-631a-42f0-98ad-80d98c9c9db6">

Can not find a way to get rid of this. Already checked the truested sender and it is the correct address @MohammedTaka

**Comment by MohammedTaka** [comment]
@maikelordaz zaynfi should approve our contract

**Comment by maikelordaz** [comment]
@MohammedTaka It is approved. The same happens on their fork, but right now the test is running on goerli because I had to restart the fork every ten minutes
<img width="496" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/4f64d9bb-5f36-4ed5-830e-2c3f5c6033ed">

**Comment by MohammedTaka** [comment]
@maikelordaz report to ammar

**Comment by elallamTaka** [comment]
@maikelordaz So it works on goerli and fails on fork?

**Comment by MohammedTaka** [comment]
@elallamTaka happens on both

**Comment by maikelordaz** [comment]
@elallamTaka @MohammedTaka no, I meant that the screenshots are from the current test forking goerli. The fork on try ethernal failed a lot without previous notice and always had to restart the fork. The problem is calling `depositYG` from `startTerm`

**Comment by maikelordaz** [comment]
Reported to Ammar on telegram

**Comment by elallamTaka** [comment]
Yeah, it doesnt make sense that calling starTerm on Goerli working but failing on their fork?

**Comment by elallamTaka** [comment]
https://takadao.atlassian.net/browse/TT-1433
