### ISSUE TITLE
totalYieldGenerated requires function call from ZaynFi

### ISSUE THREAD

**Issue by MohammedTaka** [TakafulDAO/takaturn#9]
https://github.com/TakafulDAO/takaturn-phase-2/blob/518c7c9df3f681f248d4915619dfee7452e82190/contracts/version-2/facets/GettersFacetV2.sol#L377

Current is:
(yield.totalDeposit - yield.currentTotalDeposit)

should be:
(yield.totalYieldDeposit - IZaynVaultV2TakaoDao.balanceOf())

**Comment by maikelordaz** [comment]
Commit 30a82a8

**Comment by maikelordaz** [comment]
This one should be (yield.totalYieldDeposit - IZaynVaultV2TakaoDao.balanceOf(termId)) or (yield.totalYieldDeposit - IZaynVaultV2TakaoDao.balance)? On my notes I have that balanceOf returns the term's shares, nut don't remember what Ammar told us about balance

**Comment by MohammedTaka** [comment]
balanceOf returns shares yes. You can get the price of a share with the new function
getPricePerFullShare() from zaynfi vault

**Comment by maikelordaz** [comment]
Commit e30962b

**Comment by MohammedTaka** [comment]
We want to return the eth amount, not shares

https://github.com/TakafulDAO/takaturn-phase-2/blob/e30962b252c74e6d14823f6622e395dd67fad17d/contracts/facets/GettersFacet.sol#L438

It should multiply the shares with getPricePerFullShare()

**Comment by MohammedTaka** [comment]
This is fixed by a new _sharesToEth function which has been mentioned in https://github.com/TakafulDAO/takaturn-phase-2/issues/78
