### ISSUE TITLE
Term State not changing after call to startTerm (unusual bug??) 

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#91]
Term state should transition to ActiveTerm. But after call state is stuck at isInitialized. Reported by @kkharji 

https://github.com/TakafulDAO/takaturn-phase-2/blob/6410733eb3a1c8a4af68cab43cbf84e291188e6a/contracts/facets/TermFacet.sol#L194

**Comment by MohammedTaka** [comment]
@maikelordaz you fixed this right? Could you provide the commit?

**Comment by maikelordaz** [comment]
Yes. It was on the PR. Commit efc6df7
