### ISSUE TITLE
[Critical] Overflow bug when getting withdrawable user balance 

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#93]
Found while testing with @kkharji. 
Calling this function for term ID 164, and user address 0xd26235AF7919C81470481fF4436B5465B0bbF6F2 caused the following error.
Note that the current cycle was the final cycle of the term, fund state was accepting contributions. Edge case?

`Panic due to OVERFLOW(17) (action="call", data="0x4e487b710000000000000000000000000000000000000000000000000000000000000011", reason="Panic due to OVERFLOW(17)", transaction={ "data": "0x77778baf00000000000000000000000000000000000000000000000000000000000000a4000000000000000000000000d26235af7919c81470481ff4436b5465b0bbf6f2", "to": "0x9FBDb4A7E0fe9EA27148Dcd165a61AFEF4fAFf89" }, invocation=null, revert={ "args": [ 17 ], "name": "Panic", "signature": "Panic(uint256)" }, code=CALL_EXCEPTION, version=6.7.1)`

https://github.com/TakafulDAO/takaturn-phase-2/blob/cf9c473d69a7fd1d2b6106c592ad13ca06bd66bf/contracts/facets/GettersFacet.sol#L197-L228

**Comment by MohammedTaka** [comment]
`allowedWithdrawal = minRequiredCollateral - userCollateral + availableYield; `

Should be

`allowedWithdrawal = userCollateral - minRequiredCollateral  + availableYield; `

**Comment by maikelordaz** [comment]
Fixed and merged. Commit 25c37a8
