### ISSUE TITLE
[Critical] User will be able to claim his yield anytime during a term

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#96]
A user can call this function to withdraw his yield any time he wants. This may mess up withdrawal logic. 

https://github.com/TakafulDAO/takaturn-phase-2/blob/a82f3562865f0d46f8add530297f297d62b8d48f/contracts/facets/YGFacetZaynFi.sol#L87-L92

**Comment by MohammedTaka** [comment]
This is by design, the availableYield value is only updated when a withdrawal is done.
