### ISSUE TITLE
[Critical] User cannot withdraw his partial collateral if his yield was 0

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#97]
1) User calles `withdrawCollateral `to withdraw partial eth
 2)` claimAvailableYield` failes due to` require(availableYield > 0, "No yield to withdraw"); `is causing the transaction fail. 

Fix, `withdrawCollateral `should not fail if the user's yield balance is 0 (maybe the exchange is not doing well or he wants to partially withdraw early). 

https://github.com/TakafulDAO/takaturn-phase-2/blob/a82f3562865f0d46f8add530297f297d62b8d48f/contracts/facets/CollateralFacet.sol#L193-L195

**Comment by maikelordaz** [comment]
Commit 4150526 and cf486d3. On PR

**Comment by MohammedTaka** [comment]
@elallamTaka please confirm it's fixed

**Comment by elallamTaka** [comment]
The change should fix it, but we need to set up proper unit tests to check for all possible cases, including edge cases.
