### ISSUE TITLE
[Critical] getJoinedTermsByState produces panic code 50

### ISSUE THREAD

**Issue by elallamTaka** [TakafulDAO/takaturn#99]
To reproduce, call function with state= Active Term and user = 0xd26235af7919c81470481ff4436b5465b0bbf6f2

![image](https://github.com/TakafulDAO/takaturn-phase-2/assets/130288542/5723a185-5aef-424d-b2a3-1bc179a3b590)

https://github.com/TakafulDAO/takaturn-phase-2/blob/50ea703705210193ecbc4d3d39c899b81d90c4e6/contracts/facets/GettersFacet.sol#L58-L79

**Comment by maikelordaz** [comment]
Commit 4774c36. On PR

**Comment by MohammedTaka** [comment]
@elallamTaka please confirm that it is fixed
